"""remove merchant_id from payment

Revision ID: 0dda561dee54
Revises: b1d14a1a7bc1
Create Date: 2026-03-12 18:28:55.274703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dda561dee54'
down_revision: Union[str, Sequence[str], None] = 'b1d14a1a7bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payments_merchant_id_fkey'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'merchant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('merchant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payments_merchant_id_fkey'), 'payments', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###
