"""replace phone with email in merchants

Revision ID: 4dffdb0c3ff4
Revises: cbe24768c0bc
Create Date: 2026-02-26 01:05:45.057017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dffdb0c3ff4'
down_revision: Union[str, Sequence[str], None] = 'cbe24768c0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('merchants', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('merchants', 'email')
    # ### end Alembic commands ###
