"""add alias to merchant

Revision ID: 95d725f9d4c5
Revises: 9e35d56812bc
Create Date: 2026-03-20 15:15:59.752485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d725f9d4c5'
down_revision: Union[str, Sequence[str], None] = '9e35d56812bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('alias', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'alias')
    # ### end Alembic commands ###
