"""add wallet to merchant and payer receiver to payment

Revision ID: b1d14a1a7bc1
Revises: 6d89befdf2b0
Create Date: 2026-03-12 17:52:44.205530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d14a1a7bc1'
down_revision: Union[str, Sequence[str], None] = '6d89befdf2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('wallet', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('payer_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'merchants', ['payer_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'merchants', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'receiver_id')
    op.drop_column('payments', 'payer_id')
    op.drop_column('merchants', 'wallet')
    # ### end Alembic commands ###
